import CCFeature from '@/Feature/CWFeature';
import ElecFeature from '@/Feature/ElecFeature';
import HKFeature from '@/Feature/HKFeature';
import React from 'react'

const page = () => {
  return (
    <div>
      <HKFeature/>
      <ElecFeature/>
      <CCFeature/>
    </div>
  )
}

export default page

export const metadata = {
    title: "SKFMS - Services",
    description: "Generated by create next app",
  };