import CCFeature from '@/Component/CCFeature';
import ElecFeature from '@/Component/ElecFeature';
import HKFeature from '@/Component/HKFeature';
import React from 'react'

const page = () => {
  return (
    <div>
      <HKFeature/>
      <ElecFeature/>
      <CCFeature/>
    </div>
  )
}

export default page

export const metadata = {
    title: "SKFMS - Services",
    description: "Generated by create next app",
  };