import AllServices from '@/Component/AllServices';
import React from 'react'

const page = () => {
  return (
    <div>
      <AllServices/>
    </div>
  )
}

export default page

export const metadata = {
    title: "SKFMS - Services",
    description: "Generated by create next app",
  };