import ASection from "@/Component/ASection";
import Image from "next/image";

export default function Home() {
  return (
    <div >
      <ASection/>
    </div>
  );
}

export const metadata = {
  title: "SKFMS - Home",
  description: "Generated by create next app",
};