import AllServices from "@/Component/AllServices";
import ASection from "@/Component/ASection";

export default function Home() {
  return (
    <div >
      <ASection/>
      <AllServices/>
    </div>
  );
}

export const metadata = {
  title: "SKFMS - Home",
  description: "Generated by create next app",
};