import React from 'react'

const page = () => {
  return (
    <div>
      about
    </div>
  )
}

export default page

export const metadata = {
    title: "SKFMS - About",
    description: "Generated by create next app",
  };