import ASection from "@/Component/ASection";
import React from "react";


const page = () => {
  return (
    <ASection/>
  )
}

export default page

export const metadata = {
    title: "SKFMS - About",
    description: "Generated by create next app",
  };